### ISSUE TITLE
Checkpoints not loading

### ISSUE THREAD

**Issue by Simsk8er** [mut-ex/gligen-gui#4]
I ran this fine the first time, closed it all down came back a couple hours later and I keep getting this.  The GUI loads and I see everything except the checkpoints won't load.  The first time I ran it, it showed all my checkpoints I have.

PS D:\StableDiffusion\gligen\gligen-gui> flask --app 'gligen_gui:create_app(8188)' run --port 5000
 * Serving Flask app 'gligen_gui:create_app(8188)'
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5000
Press CTRL+C to quit
127.0.0.1 - - [17/Feb/2024 02:13:39] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [17/Feb/2024 02:13:40] "GET /static/toast.css HTTP/1.1" 304 -
127.0.0.1 - - [17/Feb/2024 02:13:40] "GET /static/dice.svg HTTP/1.1" 304 -
127.0.0.1 - - [17/Feb/2024 02:13:40] "GET /static/recycle.svg HTTP/1.1" 304 -
127.0.0.1 - - [17/Feb/2024 02:13:40] "GET /static/script.js HTTP/1.1" 304 -
127.0.0.1 - - [17/Feb/2024 02:13:40] "GET /static/add.svg HTTP/1.1" 304 -
Get Object Info:  CheckpointLoaderSimple
Get Object Info:  KSampler
Get Object Info:  LoraLoaderModelOnly
127.0.0.1 - - [17/Feb/2024 02:13:40] "GET /static/dice-active.svg HTTP/1.1" 304 -
127.0.0.1 - - [17/Feb/2024 02:13:40] "GET /static/delete.svg HTTP/1.1" 304 -
[2024-02-17 02:13:42,554] ERROR in app: Exception on /object_info/KSampler [GET]
Traceback (most recent call last):
  File "C:\Users\ryan8\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "C:\Users\ryan8\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1283, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\ryan8\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1329, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\ryan8\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\ryan8\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1038, in _send_output
    self.send(msg)
  File "C:\Users\ryan8\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 976, in send
    self.connect()
  File "C:\Users\ryan8\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 942, in connect
    self.sock = self._create_connection(
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ryan8\AppData\Local\Programs\Python\Python311\Lib\socket.py", line 851, in create_connection
    raise exceptions[0]
  File "C:\Users\ryan8\AppData\Local\Programs\Python\Python311\Lib\socket.py", line 836, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ryan8\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ryan8\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ryan8\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ryan8\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\StableDiffusion\gligen\gligen-gui\gligen_gui\__init__.py", line 27, in get_object_info
    response = urllib.request.urlopen(req)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ryan8\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ryan8\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 519, in open
    response = self._open(req, data)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ryan8\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ryan8\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "C:\Users\ryan8\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 1377, in http_open
    return self.do_open(http.client.HTTPConnection, req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ryan8\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10061] No connection could be made because the target machine actively refused it>
127.0.0.1 - - [17/Feb/2024 02:13:42] "GET /object_info/KSampler HTTP/1.1" 500 -
[2024-02-17 02:13:42,555] ERROR in app: Exception on /object_info/LoraLoaderModelOnly [GET]
Traceback (most recent call last):
  File "C:\Users\ryan8\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "C:\Users\ryan8\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1283, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\ryan8\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1329, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\ryan8\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\ryan8\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1038, in _send_output
    self.send(msg)
  File "C:\Users\ryan8\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 976, in send
    self.connect()
  File "C:\Users\ryan8\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 942, in connect
    self.sock = self._create_connection(
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ryan8\AppData\Local\Programs\Python\Python311\Lib\socket.py", line 851, in create_connection
    raise exceptions[0]
  File "C:\Users\ryan8\AppData\Local\Programs\Python\Python311\Lib\socket.py", line 836, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ryan8\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ryan8\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ryan8\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ryan8\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\StableDiffusion\gligen\gligen-gui\gligen_gui\__init__.py", line 27, in get_object_info
    response = urllib.request.urlopen(req)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ryan8\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ryan8\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 519, in open
    response = self._open(req, data)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ryan8\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ryan8\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "C:\Users\ryan8\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 1377, in http_open
    return self.do_open(http.client.HTTPConnection, req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ryan8\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10061] No connection could be made because the target machine actively refused it>
127.0.0.1 - - [17/Feb/2024 02:13:42] "GET /object_info/LoraLoaderModelOnly HTTP/1.1" 500 -
[2024-02-17 02:13:42,556] ERROR in app: Exception on /object_info/CheckpointLoaderSimple [GET]
Traceback (most recent call last):
  File "C:\Users\ryan8\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "C:\Users\ryan8\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1283, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\ryan8\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1329, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\ryan8\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\ryan8\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1038, in _send_output
    self.send(msg)
  File "C:\Users\ryan8\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 976, in send
    self.connect()
  File "C:\Users\ryan8\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 942, in connect
    self.sock = self._create_connection(
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ryan8\AppData\Local\Programs\Python\Python311\Lib\socket.py", line 851, in create_connection
    raise exceptions[0]
  File "C:\Users\ryan8\AppData\Local\Programs\Python\Python311\Lib\socket.py", line 836, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ryan8\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ryan8\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ryan8\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ryan8\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\StableDiffusion\gligen\gligen-gui\gligen_gui\__init__.py", line 27, in get_object_info
    response = urllib.request.urlopen(req)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ryan8\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ryan8\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 519, in open
    response = self._open(req, data)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ryan8\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ryan8\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "C:\Users\ryan8\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 1377, in http_open
    return self.do_open(http.client.HTTPConnection, req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ryan8\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10061] No connection could be made because the target machine actively refused it>
127.0.0.1 - - [17/Feb/2024 02:13:42] "GET /object_info/CheckpointLoaderSimple HTTP/1.1" 500 -

**Comment by H4sh3** [comment]
Do you have https://github.com/comfyanonymous/ComfyUI running on port 8188?
This project is using it to generate the images.

**Comment by Simsk8er** [comment]
> Do you have https://github.com/comfyanonymous/ComfyUI running on port 8188? This project is using it to generate the images.

Hey!  I do have it running on port 8188, but when I read this I decided to run comfyUI generate an image and it worked so I then ran the gligen gui, and it worked!  did I need to open comfyUI first?  Sorry I understand all this to an extent, I just had never used github a WHOLE lot, used to doing the 1 click installers.  But this is so cool.
